Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -19,9 +19,7 @@ jobs:
         run: docker compose down
 
       - name: Build and start containers
-        run: |
-             whoami
-             sudo -n docker compose up -d --build || echo "Sudo failed" # Build fresh images and start containers
+        run: sudo docker compose up -d --build || echo "Sudo failed" # Build fresh images and start containers
 
       - name: Health check
         run: |
